# version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.11.2
    hostname: wazuh-manager
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - ./config/wazuh/ossec.conf:/var/ossec/etc/ossec.conf
    restart: always

  suricata:
    image: jasonish/suricata:latest
    command: -i eth0
    volumes:
      - ./config/suricata/suricata.yaml:/etc/suricata/suricata.yaml
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
