version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: cs-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - cs-db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: cs-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: cs-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  cs-db-data:
